### ISSUE TITLE
new GUI cant run on M1 Mac

### ISSUE THREAD

**Issue by blacklein** [Kenshin9977/video-dl#16]
run in virtual env 3.10.9 after installing all missing modules, it shows pop-up windows with error below
<img width="851" alt="截屏2022-12-26 09 11 07" src="https://user-images.githubusercontent.com/69177971/209487490-a18f03fe-8d8c-4072-979e-b3f93dec0a82.png">

```
❯ python3 app.py
Unhandled error processing page session 85830c5c-ad7e-4e2f-bfa4-faa6d17df820: Traceback (most recent call last):
  File "/Users/usrname/.virtualenvs/33-video-dl-310-9-shared/lib/python3.10/site-packages/flet/flet.py", line 212, in on_session_created
    session_handler(page)
  File "/Users/usrname/Downloads/video-dl-master 2/gui_flet.py", line 764, in videodl_fletgui
    videodl_app = VideodlApp(page)
  File "/Users/usrname/Downloads/video-dl-master 2/gui_flet.py", line 50, in __init__
    self.media_link = ft.TextField(
TypeError: TextField.__init__() got an unexpected keyword argument 'dense'
```

btw maybe author can consider code gui with CustomTkinter
https://github.com/TomSchimansky/CustomTkinter

**Comment by Kenshin9977** [comment]
Ah, it's probably because this argument is still only in flet's pre-release.
Try:
`pip uninstall flet`
`pip install flet --pre`
To install the latest pre-release version
